apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: olly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: olly-alert-rules
  namespace: olly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
